name: 'simulation'

on: [ push, pull_request ]

jobs:

  simulation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - run: docker run --rm -tv $(pwd):/src -w /src/sim -e BUILD_NAME=ACCEPTANCE ghdl/vunit:llvm make all
